ATTACH TABLE _ UUID '2dd6d67b-4d52-4dbc-a380-6ca59d1de087'
(
    `measurement_uid` String,
    `input` Nullable(String),
    `report_id` String,
    `measurement_start_time` DateTime64(3, 'UTC'),
    `software_name` String,
    `software_version` String,
    `test_name` String,
    `test_version` String,
    `probe_asn` Int32,
    `probe_cc` String,
    `probe_as_org_name` String,
    `probe_as_cc` String,
    `probe_as_name` String,
    `network_type` String,
    `platform` String,
    `origin` String,
    `engine_name` String,
    `engine_version` String,
    `architecture` String,
    `resolver_ip` String,
    `resolver_asn` Int32,
    `resolver_cc` String,
    `resolver_as_org_name` String,
    `resolver_as_cc` String,
    `resolver_is_scrubbed` Int8,
    `resolver_asn_probe` Int32,
    `resolver_as_org_name_probe` String,
    `bucket_date` Nullable(String),
    `observation_id` String,
    `created_at` Nullable(DateTime64(3, 'UTC')),
    `hirl_sent_0` Nullable(String),
    `hirl_sent_1` Nullable(String),
    `hirl_sent_2` Nullable(String),
    `hirl_sent_3` Nullable(String),
    `hirl_sent_4` Nullable(String),
    `hirl_received_0` Nullable(String),
    `hirl_received_1` Nullable(String),
    `hirl_received_2` Nullable(String),
    `hirl_received_3` Nullable(String),
    `hirl_received_4` Nullable(String),
    `hirl_failure` Nullable(String),
    `hirl_success` Nullable(Int8),
    `hfm_diff` Nullable(String),
    `hfm_failure` Nullable(String),
    `hfm_success` Nullable(Int8)
)
ENGINE = ReplacingMergeTree
ORDER BY (measurement_uid, measurement_start_time)
SETTINGS index_granularity = 8192
