#!/bin/bash
DOCS_ROOT=dist/docs/
REPO_NAME="ooni/data"
MAIN_BRANCH="main"
COMMIT_HASH=$(git rev-parse --short HEAD)

mkdir -p $DOCS_ROOT
mkdir -p $DOCS_ROOT/img

strip_title() {
    # Since the title is already present in the frontmatter, we need to remove
    # it to avoid duplicate titles
    local infile="$1"
    cat $infile | awk 'BEGIN{p=1} /^#/{if(p){p=0; next}} {print}'
}

generate_doc() {
    local order="$1"
    local slug="$2"
    local input_file="$3"
    local output_file="$4"
    local title="$5"
    local description="$6"

    cat <<EOF>"$DOCS_ROOT/$output_file"
---
# Do not edit! This file is automatically generated
# version: $REPO_NAME/$input_file:$COMMIT_HASH
title: $title
description: $description
slug: $slug
sidebar:
    order: $order
---
EOF
    echo "[edit file](https://github.com/$REPO_NAME/edit/$MAIN_BRANCH/$input_file)" >> "$DOCS_ROOT/$output_file"
    strip_title "$input_file" >> "$DOCS_ROOT/$output_file"
}


generate_doc 0 "data" "Readme.md" "00-index.md" "Accessing OONI data" "How to access OONI data"
generate_doc 1 "data/oonidata" "oonidata/Readme.md" "01-oonidata.md" "OONI Data CLI" "Using the oonidata command line interface"
cp oonidata/docs/img/* $DOCS_ROOT/img/
generate_doc 2 "data/oonidata-analysis-db" "oonidata/docs/DataAnalysisDB.md" "03-oonidata-analysis-db.md" "OONI Data Analysis DB" "OONI Data Analysis DB"
generate_doc 3 "data/pipeline-design" "oonipipeline/Design.md" "02-pipeline-design.md" "OONI Data Pipeline design" "Design for OONI Pipeline v5"
generate_doc 4 "data/pipeline" "oonipipeline/Readme.md" "03-pipeline.md" "OONI Data Pipeline v5" "OONI Data Pipeline v5"
