#!/bin/bash
DOCS_ROOT=dist/docs/
REPO_NAME="ooni/data"
COMMIT_HASH=$(git rev-parse --short HEAD)

mkdir -p $DOCS_ROOT

strip_title() {
    # Since the title is already present in the frontmatter, we need to remove
    # it to avoid duplicate titles
    local infile="$1"
    cat $infile | awk 'BEGIN{p=1} /^#/{if(p){p=0; next}} {print}'
}

cat <<EOF>$DOCS_ROOT/00-index.md
---
# Do not edit! This file is automatically generated
# version: $REPO_NAME:$COMMIT_HASH
title: OONI Data
description: OONI Data documentation
slug: data
---
EOF
strip_title Readme.md >> $DOCS_ROOT/00-index.md

cat <<EOF>$DOCS_ROOT/01-oonidata.md
---
# Do not edit! This file is automatically generated
# version: $REPO_NAME:$COMMIT_HASH
title: Accessing OONI Data
description: How to access OONI Data
slug: data/oonidata
---
EOF
strip_title oonidata/Readme.md >> $DOCS_ROOT/01-oonidata.md

cat <<EOF>$DOCS_ROOT/02-pipeline.md
---
# Do not edit! This file is automatically generated
# version: $REPO_NAME:$COMMIT_HASH
title: OONI Data Pipepline
description: OONI Data Pipeline documentation
slug: data/pipeline
---
EOF
strip_title oonipipeline/Readme.md >> $DOCS_ROOT/02-pipeline.md
