#!/bin/bash
set -euo pipefail

DOCS_ROOT=dist/docs/
ASSETS_ROOT=dist/public/
REPO_NAME="ooni/data"
MAIN_BRANCH="main"
COMMIT_HASH=$(git rev-parse --short HEAD)
BLOB="https://github.com/$REPO_NAME/blob/$MAIN_BRANCH"
TREE="https://github.com/$REPO_NAME/tree/$MAIN_BRANCH"

rm -rf $DOCS_ROOT $ASSETS_ROOT
mkdir -p $DOCS_ROOT/img
mkdir -p $DOCS_ROOT/pipeline
mkdir -p $ASSETS_ROOT

strip_title() {
    # Since the title is already present in the frontmatter, we need to remove
    # it to avoid duplicate titles
    local infile="$1"
    cat $infile | awk 'BEGIN{p=1} /^#/{if(p){p=0; next}} {print}'
}

# The pipeline documents cross-reference each other with relative paths so they
# stay readable in the repository and on GitHub. On the docs site those have to
# become slugs. Anchors are preserved: foo.md#bar -> /data/foo#bar
#
# The first block also replaces the link *text*, since every cross-reference is
# written as [filename.md](filename.md): a bare filename reads correctly next to
# the file in the repository, and as a document title on the site. The second
# block catches any reference whose text was written differently.
rewrite_links() {
    sed -E \
        -e 's|\[requirements\.md\]\(requirements\.md\)|[Requirements](/data/pipeline-design)|g' \
        -e 's|\[architecture\.md\]\(architecture\.md\)|[Architecture](/data/pipeline)|g' \
        -e 's|\[ontology\.md\]\(ontology\.md\)|[Ontology](/data/pipeline-ontology)|g' \
        -e 's|\[user-guide\.md\]\(user-guide\.md\)|[User guide](/data/pipeline-user-guide)|g' \
        -e 's|\[developer-guide\.md\]\(developer-guide\.md\)|[Developer guide](/data/pipeline-developer-guide)|g' \
        -e 's|\[implementation-plan\.md\]\(implementation-plan\.md\)|[Implementation plan](/data/pipeline-implementation-plan)|g' \
        -e 's|\[label-corpus-design\.md\]\(label-corpus-design\.md\)|[Label corpus](/data/pipeline-label-corpus)|g' \
        -e 's|\[migration-notes\.md\]\(migration-notes\.md\)|[Migration notes](/data/pipeline-migration-notes)|g' \
        -e 's|\]\(requirements\.md(#[^)]*)?\)|](/data/pipeline-design\1)|g' \
        -e 's|\]\(architecture\.md(#[^)]*)?\)|](/data/pipeline\1)|g' \
        -e 's|\]\(ontology\.md(#[^)]*)?\)|](/data/pipeline-ontology\1)|g' \
        -e 's|\]\(user-guide\.md(#[^)]*)?\)|](/data/pipeline-user-guide\1)|g' \
        -e 's|\]\(developer-guide\.md(#[^)]*)?\)|](/data/pipeline-developer-guide\1)|g' \
        -e 's|\]\(implementation-plan\.md(#[^)]*)?\)|](/data/pipeline-implementation-plan\1)|g' \
        -e 's|\]\(label-corpus-design\.md(#[^)]*)?\)|](/data/pipeline-label-corpus\1)|g' \
        -e 's|\]\(migration-notes\.md(#[^)]*)?\)|](/data/pipeline-migration-notes\1)|g' \
        -e 's|\]\(labeler\.html\)|](/tools/labeler)|g' \
        -e 's|\]\(event-labeler\.html\)|](/event-labeler.html)|g' \
        -e 's|\]\(explorer-mockup\.html\)|](/explorer-mockup.html)|g' \
        -e "s|\]\(analysis-evaluation\.ipynb\)|]($BLOB/docs/analysis-evaluation.ipynb)|g" \
        -e "s|\]\(labels/\)|]($TREE/docs/labels)|g" \
        -e "s|\]\(\.\./scripts/([a-zA-Z0-9_.-]+)\)|]($BLOB/scripts/\1)|g" \
        `# The handful of places a document is named in running prose rather` \
        `# than linked. Applied last, so the rules above have already consumed` \
        `# every genuine link.` \
        -e 's|cite requirements\.md\.|cite [Requirements](/data/pipeline-design).|g' \
        -e 's|(^\|[^/])label-corpus-design\.md|\1[Label corpus](/data/pipeline-label-corpus)|g'
}

generate_doc() {
    local order="$1"
    local slug="$2"
    local input_file="$3"
    local output_file="$4"
    local title="$5"
    local description="$6"

    # title and description are quoted: several contain a colon, which is not
    # valid as an unquoted YAML scalar.
    cat <<EOF>"$DOCS_ROOT/$output_file"
---
# Do not edit! This file is automatically generated
# version: $REPO_NAME/$input_file:$COMMIT_HASH
title: "${title//\"/\\\"}"
description: "${description//\"/\\\"}"
slug: $slug
sidebar:
    order: $order
---
EOF
    echo "[edit file](https://github.com/$REPO_NAME/edit/$MAIN_BRANCH/$input_file)" >> "$DOCS_ROOT/$output_file"
    strip_title "$input_file" | rewrite_links >> "$DOCS_ROOT/$output_file"
}

## Accessing OONI data, and the oonidata CLI.
generate_doc 0 "data" "Readme.md" "00-index.md" "Accessing OONI data" "How to access OONI data"
generate_doc 1 "data/oonidata" "oonidata/Readme.md" "01-oonidata.md" "OONI Data CLI" "Using the oonidata command line interface"
cp oonidata/docs/img/* $DOCS_ROOT/img/
generate_doc 2 "data/oonidata-analysis-db" "oonidata/docs/DataAnalysisDB.md" "03-oonidata-analysis-db.md" "OONI Data Analysis DB" "OONI Data Analysis DB"

## The pipeline v5 documentation set, under docs/.
##
## These land in a nested "Pipeline v5" sidebar group, which is autogenerated
## from the directory: adding a document here is enough to make it appear.
##
## Two slugs are inherited from the documents these supersede, so existing
## links keep working: data/pipeline-design (was the Design.md document, now
## Requirements) and data/pipeline (was the oonipipeline Readme, now
## Architecture).
generate_pipeline_doc() {
    local order="$1"
    local slug="$2"
    local name="$3"
    local output_file="$4"
    local title="$5"
    local description="$6"
    generate_doc "$order" "$slug" "docs/$name.md" "pipeline/$output_file" "$title" "$description"
}

generate_pipeline_doc 0 "data/pipeline-design" "requirements" "00-requirements.md" \
    "Requirements" "What the OONI data pipeline must achieve, and how designs are assessed against it"
generate_pipeline_doc 1 "data/pipeline" "architecture" "01-architecture.md" \
    "Architecture" "How the OONI data pipeline is put together: processing tiers, infrastructure and tradeoffs"
generate_pipeline_doc 2 "data/pipeline-ontology" "ontology" "02-ontology.md" \
    "Ontology" "What the pipeline entities mean and what the numbers claim"
generate_pipeline_doc 3 "data/pipeline-user-guide" "user-guide" "03-user-guide.md" \
    "User guide" "How to consume the datasets the pipeline produces, and what the numbers support"
generate_pipeline_doc 4 "data/pipeline-developer-guide" "developer-guide" "04-developer-guide.md" \
    "Developer guide" "Working on the pipeline: local setup, common changes and the traps"
generate_pipeline_doc 5 "data/pipeline-implementation-plan" "implementation-plan" "05-implementation-plan.md" \
    "Implementation plan" "Where the pipeline stands today and what the next steps are"
generate_pipeline_doc 6 "data/pipeline-label-corpus" "label-corpus-design" "06-label-corpus.md" \
    "Label corpus" "The ground-truth corpora used to evaluate scoring and detection"
generate_pipeline_doc 7 "data/pipeline-migration-notes" "migration-notes" "07-migration-notes.md" \
    "Migration notes" "Operations to run by hand against a live ClickHouse cluster, in deploy order"

## Static assets referenced by the documents above. These are served from the
## docs site root, so docs/event-labeler.html becomes /event-labeler.html.
cp docs/event-labeler.html $ASSETS_ROOT/
cp docs/explorer-mockup.html $ASSETS_ROOT/
