name: End to End Data Pipeline Test

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: cache inputs and outputs
        uses: actions/cache@v5
        with:
          key: data-cache-${{ github.run_id }}
          restore-keys: |
            data-cache-
          path: |
            tests/integration/data

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman podman-compose podman-docker

      - name: Run Docker Compose with Podman
        run: |
          cd tests/integration && podman-compose up -d

      - name: Wait for Downlaoder Container to Exit
        run: |
          # Replace `your_container_name` with the name of your container
          while [ $(podman ps -q -f name=oonidata-pipeline | wc -l) -gt 0 ]; do
            echo "Container is still running..."
            sleep 5 # Wait for 5 seconds before checking again
          done
          echo "Container has exited."

      - name: Query and verify data from API
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" http://localhost:8000/api/v1/measurements?since=2026-01-01T00%3A00%3A00&until=2026-01-02T00%3A00%3A00&order_by=measurement_start_time&order=DESC&offset=0&limit=100)
          
          if [ "$response" -eq 200 ]; then
            echo "HTTP 200 OK: Data retrieved successfully."
            cat response.json # Optional: Process or display the retrieved data
          else
            echo "Failed to retrieve data. HTTP Status Code: $response"
            exit 1
          fi

      - name: Shutdown
        run: |
          cd tests/integration && podman-compose down

